version: "3.8"

services:
  postgres:
    image: postgres:15-alpine
    container_name: postgres_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: copa2022
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build: .
    container_name: backend_api
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: "postgresql://postgres:postgres@postgres:5432/copa2022?schema=public"
      ACCESS_TOKEN_SECRET: ${ACCESS_TOKEN_SECRET}
      REFRESH_TOKEN_SECRET: ${REFRESH_TOKEN_SECRET}
    depends_on:
      - postgres
    volumes:
      - .:/app
      - /app/node_modules

  frontend:
    build:
      context: ../roadmap-topico-react
      dockerfile: Dockerfile
    container_name: frontend_app
    ports:
      - "5173:5173"
    depends_on:
      - backend
    volumes:
      - ../roadmap-topico-react:/app
      - /app/node_modules

volumes:
  postgres_data:
